[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://vlhiojvougcjiwctfnpd.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsaGlvanZvdWdjaml3Y3RmbnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjM2MTMsImV4cCI6MjA2NDAzOTYxM30.JZtfAAyFNdIPnRqNkS_v8I_oM5wr9OKQOQx00Hq_LoE"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Fonction programmée pour vérifier les heures passées toutes les 5 minutes
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

[plugins.inputs]
  schedule = "*/5 * * * *"  # Toutes les 5 minutes